### PR TITLE
Add/integration logic

### PR DESCRIPTION
**Pull request by wcjohnson11**
This PR gets this integration ready for a 1.0.0 release. There's a limited set of properties that we can currently pass to google adwords and those are all included here. We can try to add more at a future if Google opens up their API to accept more fields.

@jgershen @ndhoule @hankim813

### CODE REVIEW

**Comment by wcjohnson11** [comment]
I'm going to refactor the metadata setting to work alongside the clientside integration

**Comment by wcjohnson11** [comment]
This change has been made.

**Comment by wcjohnson11** [comment]
Docs PR - https://github.com/segmentio/site-docs/pull/1465

After the last PR, metadata won't need any changes to the settings other than updating platforms this supports.

**Comment by jgershen** [comment]
nice, LGTM!

**Pull request merged**
